- frontend/src/pages/InputForm.tsx
> Disable button without projectId

- frontend/src/pages/Reactions.tsx
Me and @Hardins spotted this lines that are duplicates of the lines inside try-catch (line 13-14)
> Remove redundant lines

- .github/workflows/Black.yml
Fixing usage of pyproject (limited by Python version) and "uses" with incorrect spelling in original file.
> 121 add black code formatting check to GitHub actions

- backend/src/acidwatch_api/local_db.py
- backend/src/acidwatch_api/project_endpoints.py
- **Remove unused imports**
- **Add a dummy test database**
> Create test database

- frontend/src/api/api.tsx
Prefix proxy url with / to make sure it is not treated as relative url
> Oasis proxy now working

- frontend/src/pages/InputForm.tsx
> Rename settings to model settings

- frontend/src/api/api.tsx
- frontend/src/dto/ExperimentResult.tsx
Minor change in dataformat from Oasis -> quick fix to handle this
> Fix: handle new data format

- backend/src/acidwatch_api/models/datamodel.py
- frontend/src/api/api.tsx
- frontend/src/functions/Formatting.tsx
- frontend/src/pages/ProjectListContent.tsx
- frontend/src/pages/SimulationList.tsx
Dates are now stored in ISO format in database and rendered in the same user-friendly way in the frontend.
Solves #239
> Change date format

- frontend/src/components/BatchInput.tsx
- frontend/src/components/SaveResultButton.tsx
- frontend/src/pages/InputForm.tsx
- frontend/src/pages/ProjectList.tsx
- frontend/src/pages/ResultsPage.tsx
- frontend/src/pages/SimulationList.tsx
As old results from api queries are cached, these should be used on render. Usequery will still query the api for new values,
which are displayed should the value update.
In addition, this change will not stop the page from rendering if the query is either loading or having an error if the result is
already cached.
> Improve conditional rendering

- README.md
- frontend/src/App.tsx
- frontend/src/components/SideBar.tsx
- **Fix minor grammar errors**
- **Removed empty settings page**
- **Use models for referencing calculation page**
> Several minor fixes

- frontend/src/components/SaveResultButton.tsx
> Prevent acidwatch from saving invalid simulation names

- frontend/src/pages/SimulationList.tsx
> Introduce conditional rendering of simulations table

- backend/src/acidwatch_api/models/co2spec.py
> Use correct co2 spec keys for results

- frontend/src/App.tsx
- frontend/src/components/TopBar.tsx
- frontend/src/pages/HelpPage.tsx
Adds `/help` page accessible from clicking on the question mark in the top right.
> Add help page

- frontend/src/pages/Home.tsx
> Update landing page with welcome message

- backend/src/acidwatch_api/models/model_config.py
- frontend/src/pages/InputForm.tsx
> Fix input concentration max ppm to 1000000

- frontend/src/components/InputSettings.tsx
Cleaning up and removing unused stuff
Closes: #342
> Simplify input settings component

- frontend/src/pages/InputForm.tsx
`<EdsProvider density="compact">` view should be used only on Select model div. When used on the whole page it compressed all elements
> Apply compact view only to Select model

- backend/src/acidwatch_api/db_client.py
> fix: project access, user is able to se public projects results

- frontend/src/App.tsx
- frontend/src/components/SideBar.tsx
https://github.com/user-attachments/assets/de389808-bc9e-44e2-ba00-c141f02caa24
> Set active color on sidebar menu

- frontend/src/components/TopBar.tsx
> Improve layout on profile button

- frontend/src/App.tsx
- frontend/src/components/SaveButton.tsx
- frontend/src/components/SaveResult.tsx
- frontend/src/pages/Results.tsx
This re-adds/partly fix loading results from db.
> Fix loading results from db

- frontend/src/components/ModelSelect.tsx
This PR:
1. Fixes grammar/syntax issue in the title
2. Moves the description so it's always at the bottom
3. Uses EDS Typography and `<pre>` tag instead of manual `<br/>`.
> Refactor model description in frontend

- frontend/src/components/TopBar.tsx
> Make the logo link to home

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/BarChart.tsx
Using chartjs-plugin-zoom.
Lots of options, this PR just adds zoom on y axis using left mouse button.
Check this for alternative ways:
https://www.chartjs.org/chartjs-plugin-zoom/latest/samples/basic.html
> Add zoom functionality to plot

- backend/src/acidwatch_api/app.py
This endpoint seems to be unused. Can we remove it?
> Remove unused results endpoint
